---
- name: Run on server 1
  hosts: "{{ grp }}"
  strategy: free
  gather_facts: no

  tasks:
    - name: Find all files in the directory
      find:
        paths: "runs/{{ grp }}/{{ proj }}"
        recurse: yes
        file_type: file
      register: files_to_fetch

    - name: Fetch each file individually
      fetch:
        src: "{{ item.path }}"
        dest: "runs/"
        flat: no
      with_items: "{{ files_to_fetch.files }}"
